Bookmark_keeper/urls.py
from django.contrib import admin
from django.urls import path
from Bookmarks import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('setings/', views.settings, name='settings'),
    path('tasks/<int:group_id>', views.tasks, name='tasks'),
    path('edit_task/<int:group_id>/<int:task_id>', views.edit_task, name='edit_task'),
    path('add_task/<int:group_id>', views.add_task, name='add_task'),
    path('edit_group/<int:group_id>', views.edit_group, name='edit_group'),
]

Bookmarks/models.py
from django.db import models

# Create your models here.


class Groups(models.Model):
    group_name = models.CharField(max_length=15, help_text="Few words to describe the type of tasks inside of the group")
    creation_date = models.DateTimeField(blank=True, auto_now=True, help_text="Exact time of creation of this group")
    number_of_tasks = models.IntegerField(default=0, help_text="Number of tasks inside the group, default is 0 after creating a group")

    class Meta:
        ordering = ["creation_date"]
        verbose_name = "Group"

    def __str__(self):
        return str(self.id) + " " + self.group_name


class Tasks(models.Model):
    group = models.ForeignKey(Groups, on_delete=models.CASCADE, help_text="Group to which this task belongs")
    task = models.CharField(max_length=60, null=False, help_text="content of the task to be done")
    creation_date = models.DateTimeField(blank=True, auto_now=True, help_text="Exact time of adding this task to the group")
    deadline = models.DateTimeField(blank=True, default=None, null=True, help_text="Deadline of this task, not obligatory, default null")
    is_finished = models.BooleanField(default=False, help_text="This field indicates if task is finished")

    class Meta:
        ordering = ['deadline', 'creation_date']
        verbose_name = "Task"

    def __str__(self):
        return str(self.group.group_name) + ":" + str(self.id) + ": " + self.task[:30] + "..."

Bookmarks/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone


class AddGroup(forms.Form):
    group_name = forms.CharField(max_length=15, label="",
                                 widget=forms.TextInput(attrs={'placeholder': 'Group Name',
                                                               'id': 'group_name'})
                                 )


class AddTask(forms.Form):
    task_name = forms.CharField(max_length=60, label="",
                                widget=forms.Textarea(attrs={'placeholder': 'Task',
                                                             'id': 'task'}))
    deadline = forms.DateTimeField(label="", required=False, input_formats=['%d/%m/%Y %H:%M'],
                                   widget=forms.TextInput(attrs={'placeholder': 'Deadline',
                                                                 "autocomplete": "off"})
                                   )


class EditTask(forms.Form):
    task = forms.CharField(max_length=60, label="",
                           widget=forms.Textarea(attrs={'placeholder': 'Task',
                                                        'id': 'edit_task'}))

    edit_deadline = forms.DateTimeField(label='', required=False, input_formats=['%d/%m/%Y %H:%M'],
                                        widget=forms.TextInput(attrs={'placeholder': 'Deadline',
                                                                      "autocomplete": "off"})
                                        )

    def clean(self):
        super(EditTask, self).clean()

        deadline = self.cleaned_data["edit_deadline"]

        if deadline < timezone.now():

            self.add_error("edit_deadline", "You've entered past date!")
            self._errors["edit_deadline"] = self.error_class(["You've entered past date!"])
            raise ValidationError("You've entered past date!")
        return self.cleaned_data


class EditGroup(forms.Form):
    group_name = forms.CharField(max_length=15, label="",
                                 widget=forms.TextInput(attrs={'placeholder': 'Group Name',
                                                               'id': 'edit_group_name'})
                                 )

Bookmark_keeper/views.py
from django.shortcuts import render


def index(request):
    return render(request, "home/index.html")


def settings(request):
    return render(request, "home/settings.html")


def tasks(request):
    return render(request, "home/task_group.html")

Bookmarks/views.py
from django.shortcuts import render, redirect
from .models import Groups, Tasks
from .forms import AddGroup, AddTask, EditTask, EditGroup
# Create your views here.


def index(request):
    groups = Groups.objects.all()
    all_tasks = Tasks.objects.all()
    context = {"groups": groups, "tasks": all_tasks}
    if request.method == 'POST':
        form = AddGroup(request.POST)

        if form.is_valid():

            new_group = Groups(group_name=form.cleaned_data["group_name"])
            new_group.save()
            context["form"] = AddGroup()

            return render(request, "home/index.html", context)
    else:
        form = AddGroup()
    context["form"] = form
    return render(request, "home/index.html", context)


def settings(request):
    groups = Groups.objects.all()
    context = {'groups': groups}
    return render(request, "home/settings.html", context)


def tasks(request, group_id):

    groups = Groups.objects.all()
    group_name = Groups.objects.get(pk=group_id).group_name
    tasks_from_group = Tasks.objects.filter(group_id__exact=group_id)
    context = {"tasks": tasks_from_group, 'groups': groups, 'group_name': group_name, 'group_id':group_id}

    if request.method == 'POST':

        if "delete-item" in request.POST:
            task_id = int(request.POST["delete-item"])
            Tasks.objects.filter(pk=task_id).delete()
        if "delete-group" in request.POST:
            Groups.objects.filter(pk=group_id).delete()
            return redirect('index')

    context["edit_form"] = EditTask()
    context["add_form"] = AddTask()
    context["edit_group"] = EditGroup(initial={'group_name': str(group_name)})

    return render(request, "home/task_group.html", context)


def edit_task(request, group_id, task_id):
    edit_form = EditTask(request.POST)
    if edit_form.is_valid():
        if edit_form.cleaned_data["edit_deadline"] == '':
            deadline = Tasks.objects.filter(pk=task_id).values()['edit_deadline']
        else:
            deadline = edit_form.cleaned_data["edit_deadline"]
        Tasks.objects.filter(pk=task_id).update(task=edit_form.cleaned_data["task"], deadline=deadline)
    return redirect('tasks', group_id)


def add_task(request, group_id):
    add_form = AddTask(request.POST)
    if add_form.is_valid():
        new_task = Tasks(group=Groups.objects.get(pk=group_id), task=add_form.cleaned_data["task_name"],
                         deadline=add_form.cleaned_data["deadline"])
        Groups.objects.filter(pk=group_id).update(number_of_tasks=Groups.objects.get(pk=group_id).number_of_tasks + 1)
        new_task.save()
    return redirect("tasks", group_id)


def edit_group(request, group_id):
    edit_group_form = EditGroup(request.POST)

    if edit_group_form.is_valid():

        Groups.objects.filter(pk=group_id).update(group_name=edit_group_form.cleaned_data["group_name"])
    return redirect('tasks', group_id)

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'home/main.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <title>BookMarks Keeper</title>
</head>
<body>
 <div class="sidebar">
        <div class="logo_content">
            <div class="logo">
                <div class="logo_name">
                    <img class="sidebar_logo" src="{% static 'home/label.png' %}" alt="doesn't work">
                </div>
                <i class='bx bx-menu' id="menu"></i>
            </div>

        </div>

        <ul class="nav_list">
            <li>
                <a href="{% url 'index' %}">
                    <i class='bx bxs-home'></i>
                    <span class="links_name">Home</span>
                </a>
            </li>
            {% for group in groups %}
                <li>
                    <a href="{% url 'tasks' group.id%}">
                        <i class='bx bx-task'></i>
                        <span class="links_name">{{ group.group_name }}</span>
                    </a>
            </li>
            {% endfor %}
            <li>
                <a href="{% url 'settings' %}">
                    <i class='bx bx-cog'></i>
                    <span class="links_name">Settings</span>
                </a>
        </li>
        </ul>


        <div class="change_theme">
            <hr>
            <i class='bx bxs-sun' ></i>

            <input type="checkbox" id="dark-mode">
            <label for="dark-mode"></label>
            <i class='bx bxs-moon' id="moon" ></i>


        </div>

    </div>

<header>
        <i class='bx bx-menu' id="btn"></i>
        <img class="label" src="{% static 'home/label.png' %}" alt="doesn't work">

</header>
{% block content %}
{% endblock %}
<script>


        let btn = document.querySelector("#menu");
        let btn2 = document.querySelector("#btn")
        let sidebar = document.querySelector(".sidebar");

        btn.onclick = function () {
            sidebar.classList.toggle("active")
        }
        btn2.onclick = function () {
            sidebar.classList.toggle("active")
        }

    //Function To Display Popup
    function div_show() {
    document.getElementById('popup_group').style.display = "block";
    }
    //Function to Hide Popup
    function div_hide(){
    document.getElementById('popup_group').style.display = "none";
    }
    function div_show_2() {
    document.getElementById('popup_group_2').style.display = "block";
    }
    //Function to Hide Popup
    function div_hide_2(){
    document.getElementById('popup_group_2').style.display = "none";
    }
    function div_show_3() {
    document.getElementById('popup_group_3').style.display = "block";
    }
    //Function to Hide Popup
    function div_hide_3(){
    document.getElementById('popup_group_3').style.display = "none";
    }
    function div_show_4() {
    document.getElementById('popup_group_4').style.display = "block";
    }
    //Function to Hide Popup
    function div_hide_4(){
    document.getElementById('popup_group_4').style.display = "none";
    }
    function div_show_5() {
    document.getElementById('popup_group_5').style.display = "block";
    }
    //Function to Hide Popup
    function div_hide_5(){
    document.getElementById('popup_group_5').style.display = "none";
    }
    $(function () {
        $("#id_deadline").datetimepicker({
            format: 'd/m/Y H:i',
        });
     });
    $(function () {
        $("#id_edit_deadline").datetimepicker({
            format: 'd/m/Y H:i',
        });
     });
    </script>
</body>
</html>

templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}
    {% load static %}
<div class="container">
{% for group in groups %}

    <a href="{% url "tasks" group.id %}">
    <div class="box">
            <h3 class="group_name">{{ group.group_name}}</h3>
            <hr class="line">
        <div class="task_list">
            <ul>

                {% for task in tasks %}
                    {% if task.group.id == group.id %}

                    <li>{{ task.task }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    </a>

 {% endfor %}

</div>
<div id="popup_group">
<!-- Popup Div Starts Here -->
    <div id="popupContact">
    <!-- Add Group Form -->
        <form action="#" id="form" method="post" name="form">
            <img id="close" src="{% static "home/close.png" %}" onclick ="div_hide()" alt="close">
            <h2>Add Group</h2>

            {% csrf_token %}
            {{ form }}
{#            <input id="add_group" name="add_group" placeholder="Group name" type="text">#}

            <input type="submit" id="submit" value="Add">
        </form>
    </div>
<!-- Popup Div Ends Here -->
</div>
<!-- Display Popup Button -->
<button id="popup" class="popup_tasks" onclick="div_show()"></button>

{% endblock %}

templates/home/settings.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
    <div class="container">
    <h1>SETTINGS</h1>
        <hr>
        <form action="#">
            {% csrf_token %}
            <label for="fonts_selector">Choose a font-style: </label>
                <select name="fonts" id="fonts_selector">
                    <option value="times_new_romans">Times New Romans</option>
                    <option value="arial">Arial</option>
                    <option value="calibri">Calibri</option>
                </select>
            <label for="font_size">Choose the font size: </label>
            <select name="font-size" id="font_size">
                <option value="12">12</option>
                <option value="14">14</option>
                <option value="16">16</option>
            </select>
            <input type="submit" id="save_fonts" value="Save">
        </form>
    </div>

{% endblock %}

templates/home/task_group.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
    <div class="task_container">
    <div class="group_name_header">
        <h2 class="group_name_2">
            {{ group_name }}
        </h2>
        <button class="delete group" id="popup" onclick="div_show_4()" >Delete</button>

                <div id="popup_group_4">
        <!-- Popup Div Starts Here -->
                    <div id="popupContact">
                    <!-- Add Group Form -->
                        <form action="#" id="form" method="post" name="form">

                            <img id="close" src="{% static "home/close.png" %}" onclick ="div_hide_4()" alt="close">
                            {% csrf_token %}
                            <h3>Delete group</h3>
                            <p>Are you sure you want to delete this group?</p>
                            <input type="hidden" name="delete-group">
                            <input type="submit" id="submit_4" value="Delete">
                        </form>
                    </div>
        <!-- Popup Div Ends Here -->
                </div>

                <button class="edit" id="popup" onclick="div_show_5()">Edit</button>
                <div id="popup_group_5">
        <!-- Popup Div Starts Here -->
                    <div id="popupContact">
                    <!-- Add Group Form -->
                        <form action="{% url "edit_group" group_id=group_id%}" id="form" method="post" name="form">
                            {% csrf_token %}
                            <img id="close" src="{% static "home/close.png" %}" onclick ="div_hide_5()" alt="close">
                            <h3>Edit Group</h3>
                            {{ edit_group }}
                            <input type="submit" id="submit_5" value="Edit">
                        </form>
                    </div>
        <!-- Popup Div Ends Here -->
                </div>
    </div>
        <hr class="group_divider_2">
        <div class="box_2">
            <ul>
            {% for task in tasks %}
                <li class="tasks">
                <span class="task">
                <i class='bx bx-task'></i>
                    {% if task.deadline %}
                        {{ task.deadline|date:"d m Y"}}: {{ task.task }}
                    {% else %}
                        {{ task.task }}

                    {% endif %}

                </span>
                <button class="delete" id="popup" onclick="div_show_2()" >Delete</button>

                <div id="popup_group_2">
        <!-- Popup Div Starts Here -->
                    <div id="popupContact">
                    <!-- Add Group Form -->
                        <form action="#" id="form" method="post" name="form">
                            {% csrf_token %}
                            <img id="close" src="{% static "home/close.png" %}" onclick ="div_hide_2()" alt="close">
                            <h3>Delete task</h3>
                            <p>Are you sure you want to delete the task?</p>
                            <input type="hidden" name="delete-item" value="{{ task.id }}">
                            <input type="submit" id="submit_2" value="Delete">
                        </form>
                    </div>
        <!-- Popup Div Ends Here -->
                </div>

                <button class="edit" id="popup" onclick="div_show_3()">Edit</button>
                <div id="popup_group_3">
        <!-- Popup Div Starts Here -->
                    <div id="popupContact">
                    <!-- Add Group Form -->
                        <form action="{% url "edit_task" group_id=group_id task_id=task.id   %}" id="form" method="post" name="form">
                            {% csrf_token %}
                            <img id="close" src="{% static "home/close.png" %}" onclick ="div_hide_3()" alt="close">
                            <h3>Edit task</h3>
                            {{ edit_form }}
                            <input type="submit" id="submit_3" value="Edit">
                        </form>
                    </div>
        <!-- Popup Div Ends Here -->
                </div>

                <hr class="task_divider">
            </li>
            {% endfor %}

            </ul>
        </div>
        <div id="popup_group">
<!-- Popup Div Starts Here -->
        <div id="popupContact">
        <!-- Add Group Form -->
            <form action="{% url "add_task" group_id=group_id %}" id="form" method="post" name="form">
                <img id="close" src="{% static "home/close.png" %}" onclick ="div_hide()" alt="close">
                <h2>Add Task</h2>

                {% csrf_token %}
                {{ add_form }}

                <input type="submit" id="submit" value="Add">
            </form>
        </div>
<!-- Popup Div Ends Here -->
</div>
<!-- Display Popup Button -->
<button id="popup" class="popup_tasks" onclick="div_show()"></button>
    </div>

{% endblock %}